In [102]:
oldplace

0                   Mataderos|
1                    La Plata|
2                   Mataderos|
3                     Liniers|
4                      Centro|
5                Gualeguaychú|
6                       Munro|
7                    Belgrano|
8                    Belgrano|
9                     Rosario|
10                    Córdoba|
11                 San Miguel|
12                   Martínez|
13               Palermo Soho|
14               Palermo Soho|
15                Bella Vista|
16                  Mataderos|
17             Barrio El Golf|
18                      Tigre|
19                    Palermo|
20             Villa Giardino|
21                    Palermo|
22          General Rodríguez|
23                      Pilar|
24                   Castelar|
25                   Castelar|
26         Barrio San Gabriel|
27        Estancias del Pilar|
28                   Castelar|
29                     Flores|
                  ...
121190                Córdoba|
121191                Córdoba|
121192                Córdoba|
121193                Córdoba|
121194                Córdoba|
121195                Córdoba|
121196                Córdoba|
121197                Córdoba|
121198                Córdoba|
121199                Córdoba|
121200                Córdoba|
121201                Córdoba|
121202                Córdoba|
121203                Córdoba|
121204                Córdoba|
121205                Córdoba|
121206                Córdoba|
121207                Escobar|
121208                Escobar|
121209               Belgrano|
121210               Martínez|
121211               Acassuso|
121212               Acassuso|
121213               Martínez|
121214             San Isidro|
121215               Belgrano|
121216                 Beccar|
121217          Villa Urquiza|
121218            Plaza Colón|
121219        Capital Federal|
Name: place_with_parent_names, Length: 121220, dtype: object

In [31]:
import pandas as pd 
import numpy as np 
import matplotlib as mpl 

feature = '.*\|(.*\|)'

#pf=pd.read_csv('properatti.csv')
#pfp=pf.groupby('place_name', as_index=False)['price_aprox_usd'].mean()

df=pd.read_csv('properatti.csv')
#df['place_with_parent_names'] = df['place_with_parent_names']\
#                                .str.extract('.*\|(.*\|)', expand=False).astype('str')

oldplace = df['place_with_parent_names']\
                               .str.extract('.*\|(.*\|)', expand=False).astype('str')
newplace = df['place_with_parent_names']\
                                .str.extract('.*\|(.*\|)..+?\|', expand=False).astype('str')
newplace

0                  Capital Federal|
1           Bs.As. G.B.A. Zona Sur|
2                  Capital Federal|
3                  Capital Federal|
4                    Mar del Plata|
5                       Entre Ríos|
6                    Vicente López|
7                  Capital Federal|
8                  Capital Federal|
9                         Santa Fe|
10                         Córdoba|
11        Bs.As. G.B.A. Zona Norte|
12                      San Isidro|
13                         Palermo|
14                         Palermo|
15                      San Miguel|
16                 Capital Federal|
17                        Nordelta|
18        Bs.As. G.B.A. Zona Norte|
19                 Capital Federal|
20                         Córdoba|
21                 Capital Federal|
22        Bs.As. G.B.A. Zona Oeste|
23                           Pilar|
24                           Morón|
25                           Morón|
26                           Tigre|
27                           Pilar|
28                           Morón|
29                 Capital Federal|
                    ...
121190                   Argentina|
121191                   Argentina|
121192                   Argentina|
121193                   Argentina|
121194                   Argentina|
121195                   Argentina|
121196                   Argentina|
121197                   Argentina|
121198                   Argentina|
121199                   Argentina|
121200                   Argentina|
121201                   Argentina|
121202                   Argentina|
121203                   Argentina|
121204                   Argentina|
121205                   Argentina|
121206                   Argentina|
121207    Bs.As. G.B.A. Zona Norte|
121208    Bs.As. G.B.A. Zona Norte|
121209             Capital Federal|
121210                  San Isidro|
121211                  San Isidro|
121212                  San Isidro|
121213                  San Isidro|
121214    Bs.As. G.B.A. Zona Norte|
121215             Capital Federal|
121216                  San Isidro|
121217             Capital Federal|
121218               Mar del Plata|
121219                   Argentina|
Name: place_with_parent_names, Length: 121220, dtype: object

In [75]:
pfp.head()

                place_name  price_aprox_usd
0   Country Maschwitz Club    311666.666667
1               los alamos     81600.000000
2               9 de Abril    270000.000000
3                   Abasto    162333.301560
4      Abril Club de Campo    736666.666667

In [76]:
#dfp=df.groupby('place_with_parent_names', as_index=False)['price_aprox_usd'].aggregate([np.mean, np.median])
#dfp.sample(10)
#dfp.groupby('place_with_parent_names')['price_aprox_usd']

                                  mean     median
place_with_parent_names
Tafí del Valle|           74310.865000   72908.77
El Molino|               152500.000000  152500.00
San Clemente|                      NaN        NaN
|                        646782.608696  550000.00
Altos de Matheu|         136500.000000  136500.00
Pehuen-có|               130000.000000  130000.00
San Antonio De Padua|    156799.603453  134500.00
Don Orione|               30582.231250   28602.67
San Fernando|            224616.780095  130000.00
Falda del Carmen|                  NaN        NaN

In [37]:
#combine?
#loco = pd.concat([oldplace, newplace], axis=1)

#d.drop_duplicates(subset=[newplace, oldplace], keep='first')
dfpp=df.pivot_table('price_aprox_usd', [newplace, oldplace], aggfunc={'price_aprox_usd':['mean', 'max', 'min', 'std', 'sum']})
#dfpp.columns = ['big', 'small', 'max', 'mean', 'min', 'std', 'sum']
#for i in oldplace:
 #   if i in newplace:
  #      dfpp.drop(dfpp.loc[df['newplace']==i].index, inplace=True)
        
#dfpp.head(50)
#dfpp.drop_duplicates(subset=[newplace, oldplace], keep='first')
#oldplace['place_with_parent_names'].value_counts
dfpp.head(50)
#loco.head(50)

                                                               max  \
place_with_parent_names place_with_parent_names
Almirante Brown|        Adrogué|                        1900000.00
                        Burzaco|                         750000.00
                        Claypole|                        150000.00
                        Don Orione|                       45000.00
                        Glew|                           1100000.00
                        Jose Marmol|                     550000.00
                        Longchamps|                      750000.00
                        Malvinas Argentinas|             125000.00
                        Ministro Rivadavia|              180000.00
                        Rafael Calzada|                  440000.00
                        San Jose|                        230000.00
Argentina|              Bs.As. G.B.A. Zona Norte|      13000000.00
                        Bs.As. G.B.A. Zona Oeste|        700000.00
                        Bs.As. G.B.A. Zona Sur|          600000.00
                        Buenos Aires Costa Atlántica|    800000.00
                        Buenos Aires Interior|          3000000.00
                        Capital Federal|                8500000.00
                        Catamarca|                       390000.00
                        Chaco|                                 NaN
                        Chubut|                           45000.00
                        Corrientes|                      400000.00
                        Córdoba|                        5900000.00
                        Jujuy|                           749000.00
                        La Pampa|                         39258.57
                        La Rioja|                         72908.77
                        Mendoza|                        1700000.00
                        Misiones|                        400000.00
                        Neuquén|                               NaN
                        Río Negro|                       580000.00
                        Salta|                          1233840.89
                        San Juan|                              NaN
                        San Luis|                        250000.00
                        Santa Fe|                        607700.00
                        Santiago Del Estero|             280000.00
                        Tierra Del Fuego|                 94781.41
                        Tucumán|                         550000.00
Avellaneda|             Avellaneda|                     4500000.00
                        Crucecita|                       360000.00
                        Dock Sud|                        128000.00
                        Gerli|                           490000.00
                        Piñeiro|                         130000.00
                        Sarandi|                         590000.00
                        Villa Dominico|                  763000.00
                        Wilde|                          2400000.00
Azul|                   Azul|                           2500000.00
Bahía Blanca|           Cabildo|                          47671.12
                        Naposta|                          11111.00
Balcarce|               Balcarce|                        250000.00
Berazategui|            Abril Club de Campo|            1100000.00
                        Altos de Hudson II|              410000.00

                                                               mean  \
place_with_parent_names place_with_parent_names
Almirante Brown|        Adrogué|                       2.788440e+05
                        Burzaco|                       1.349867e+05
                        Claypole|                      7.379161e+04
                        Don Orione|                    3.058223e+04
                        Glew|                          2.051374e+05
                        Jose Marmol|                   1.743075e+05
                        Longchamps|                    1.370335e+05
                        Malvinas Argentinas|           8.950000e+04
                        Ministro Rivadavia|            1.055688e+05
                        Rafael Calzada|                1.705983e+05
                        San Jose|                      1.091650e+05
Argentina|              Bs.As. G.B.A. Zona Norte|      3.062595e+05
                        Bs.As. G.B.A. Zona Oeste|      1.686861e+05
                        Bs.As. G.B.A. Zona Sur|        1.561009e+05
                        Buenos Aires Costa Atlántica|  1.313478e+05
                        Buenos Aires Interior|         2.329095e+05
                        Capital Federal|               4.267000e+05
                        Catamarca|                     2.543029e+05
                        Chaco|                                  NaN
                        Chubut|                        4.500000e+04
                        Corrientes|                    3.400000e+05
                        Córdoba|                       1.522596e+05
                        Jujuy|                         7.490000e+05
                        La Pampa|                      3.925857e+04
                        La Rioja|                      7.290877e+04
                        Mendoza|                       1.869967e+05
                        Misiones|                      8.469905e+04
                        Neuquén|                                NaN
                        Río Negro|                     1.955000e+05
                        Salta|                         1.737155e+05
                        San Juan|                               NaN
                        San Luis|                      1.078336e+05
                        Santa Fe|                      1.494055e+05
                        Santiago Del Estero|           1.551426e+05
                        Tierra Del Fuego|              8.384509e+04
                        Tucumán|                       9.031007e+04
Avellaneda|             Avellaneda|                    1.702554e+05
                        Crucecita|                     1.205714e+05
                        Dock Sud|                      7.148750e+04
                        Gerli|                         1.704545e+05
                        Piñeiro|                       8.066667e+04
                        Sarandi|                       1.237558e+05
                        Villa Dominico|                1.387419e+05
                        Wilde|                         1.328623e+05
Azul|                   Azul|                          1.307500e+06
Bahía Blanca|           Cabildo|                       4.767112e+04
                        Naposta|                       1.111100e+04
Balcarce|               Balcarce|                      2.500000e+05
Berazategui|            Abril Club de Campo|           7.366667e+05
                        Altos de Hudson II|            2.361818e+05

                                                             min  \
place_with_parent_names place_with_parent_names
Almirante Brown|        Adrogué|                         7571.29
                        Burzaco|                         6169.20
                        Claypole|                       15000.00
                        Don Orione|                     21872.63
                        Glew|                           20077.95
                        Jose Marmol|                    37000.00
                        Longchamps|                     20000.00
                        Malvinas Argentinas|            69000.00
                        Ministro Rivadavia|              8412.55
                        Rafael Calzada|                 42062.75
                        San Jose|                       16825.10
Argentina|              Bs.As. G.B.A. Zona Norte|       25798.49
                        Bs.As. G.B.A. Zona Oeste|       25000.00
                        Bs.As. G.B.A. Zona Sur|         38697.73
                        Buenos Aires Costa Atlántica|   35000.00
                        Buenos Aires Interior|           6231.51
                        Capital Federal|                16100.00
                        Catamarca|                      72908.77
                        Chaco|                               NaN
                        Chubut|                         45000.00
                        Corrientes|                    280000.00
                        Córdoba|                            0.00
                        Jujuy|                         749000.00
                        La Pampa|                       39258.57
                        La Rioja|                       72908.77
                        Mendoza|                        33650.20
                        Misiones|                       14020.91
                        Neuquén|                             NaN
                        Río Negro|                      65000.00
                        Salta|                          39258.57
                        San Juan|                            NaN
                        San Luis|                       66402.00
                        Santa Fe|                       69999.41
                        Santiago Del Estero|            30285.18
                        Tierra Del Fuego|               67300.41
                        Tucumán|                        18357.75
Avellaneda|             Avellaneda|                     13460.08
                        Crucecita|                      45000.00
                        Dock Sud|                       45000.00
                        Gerli|                          65000.00
                        Piñeiro|                        30000.00
                        Sarandi|                        50000.00
                        Villa Dominico|                 40000.00
                        Wilde|                          16000.00
Azul|                   Azul|                          115000.00
Bahía Blanca|           Cabildo|                        47671.12
                        Naposta|                        11111.00
Balcarce|               Balcarce|                      250000.00
Berazategui|            Abril Club de Campo|           390000.00
                        Altos de Hudson II|            120000.00

                                                                std  \
place_with_parent_names place_with_parent_names
Almirante Brown|        Adrogué|                       2.183078e+05
                        Burzaco|                       7.647648e+04
                        Claypole|                      3.617632e+04
                        Don Orione|                    7.188935e+03
                        Glew|                          2.238621e+05
                        Jose Marmol|                   8.434733e+04
                        Longchamps|                    1.011455e+05
                        Malvinas Argentinas|           2.456963e+04
                        Ministro Rivadavia|            6.070782e+04
                        Rafael Calzada|                1.208941e+05
                        San Jose|                      9.093758e+04
Argentina|              Bs.As. G.B.A. Zona Norte|      9.551011e+05
                        Bs.As. G.B.A. Zona Oeste|      1.174505e+05
                        Bs.As. G.B.A. Zona Sur|        1.551339e+05
                        Buenos Aires Costa Atlántica|  1.878289e+05
                        Buenos Aires Interior|         4.104160e+05
                        Capital Federal|               5.244953e+05
                        Catamarca|                     1.634102e+05
                        Chaco|                                  NaN
                        Chubut|                                 NaN
                        Corrientes|                    8.485281e+04
                        Córdoba|                       2.271990e+05
                        Jujuy|                                  NaN
                        La Pampa|                               NaN
                        La Rioja|                               NaN
                        Mendoza|                       2.671178e+05
                        Misiones|                      8.337480e+04
                        Neuquén|                                NaN
                        Río Negro|                     2.159745e+05
                        Salta|                         2.775420e+05
                        San Juan|                               NaN
                        San Luis|                      4.012611e+04
                        Santa Fe|                      1.490838e+05
                        Santiago Del Estero|           1.765750e+05
                        Tierra Del Fuego|              9.627787e+03
                        Tucumán|                       9.587597e+04
Avellaneda|             Avellaneda|                    4.820613e+05
                        Crucecita|                     1.149157e+05
                        Dock Sud|                      2.903768e+04
                        Gerli|                         1.333273e+05
                        Piñeiro|                       3.329665e+04
                        Sarandi|                       9.552564e+04
                        Villa Dominico|                1.313116e+05
                        Wilde|                         2.101301e+05
Azul|                   Azul|                          1.686450e+06
Bahía Blanca|           Cabildo|                                NaN
                        Naposta|                       0.000000e+00
Balcarce|               Balcarce|                               NaN
Berazategui|            Abril Club de Campo|           2.363613e+05
                        Altos de Hudson II|            1.227981e+05

                                                                sum
place_with_parent_names place_with_parent_names
Almirante Brown|        Adrogué|                       2.038349e+08
                        Burzaco|                       4.927013e+07
                        Claypole|                      3.320623e+06
                        Don Orione|                    2.446578e+05
                        Glew|                          2.010347e+07
                        Jose Marmol|                   2.562320e+07
                        Longchamps|                    1.397742e+07
                        Malvinas Argentinas|           3.580000e+05
                        Ministro Rivadavia|            6.334126e+05
                        Rafael Calzada|                6.141538e+06
                        San Jose|                      5.458251e+05
Argentina|              Bs.As. G.B.A. Zona Norte|      6.063939e+07
                        Bs.As. G.B.A. Zona Oeste|      9.952480e+06
                        Bs.As. G.B.A. Zona Sur|        2.497615e+06
                        Buenos Aires Costa Atlántica|  3.021000e+06
                        Buenos Aires Interior|         1.956440e+07
                        Capital Federal|               4.087786e+08
                        Catamarca|                     7.629088e+05
                        Chaco|                         0.000000e+00
                        Chubut|                        4.500000e+04
                        Corrientes|                    6.800000e+05
                        Córdoba|                       3.217246e+08
                        Jujuy|                         7.490000e+05
                        La Pampa|                      3.925857e+04
                        La Rioja|                      7.290877e+04
                        Mendoza|                       1.682970e+07
                        Misiones|                      3.642059e+06
                        Neuquén|                       0.000000e+00
                        Río Negro|                     9.775000e+05
                        Salta|                         3.126878e+06
                        San Juan|                      0.000000e+00
                        San Luis|                      2.588005e+06
                        Santa Fe|                      1.792866e+06
                        Santiago Del Estero|           3.102852e+05
                        Tierra Del Fuego|              5.030705e+05
                        Tucumán|                       4.334883e+06
Avellaneda|             Avellaneda|                    2.911367e+07
                        Crucecita|                     8.440000e+05
                        Dock Sud|                      5.719000e+05
                        Gerli|                         3.750000e+06
                        Piñeiro|                       4.840000e+05
                        Sarandi|                       5.321500e+06
                        Villa Dominico|                4.301000e+06
                        Wilde|                         1.727210e+07
Azul|                   Azul|                          2.615000e+06
Bahía Blanca|           Cabildo|                       4.767112e+04
                        Naposta|                       4.444400e+04
Balcarce|               Balcarce|                      2.500000e+05
Berazategui|            Abril Club de Campo|           4.420000e+06
                        Altos de Hudson II|            2.598000e+06

In [ ]:
dfpp[[dfpp['place_with_parent_names']!=]]